name: "Test Kepler Formal Action"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  #workflow_dispatch:
  #  inputs:
  #    verilog-files:
  #      description: "Verilog file glob"
  #      required: true
  #      default: "src/*.v"
  #    top-module:
  #      description: "Top-level module name"
  #      required: true
  #      default: "top"

jobs:
  test-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run keplertech formal action
        uses: ./.  # local composite action
        with:
          design_home: "benchs/vexriscv"
          design_config: "benchs/vexriscv/synth.ys"

      - name: Upload design.stats
        uses: actions/upload-artifact@v4
        with:
          name: design-stats
          path: design.stats
